#!/usr/bin/env python3
"""Pin Python's Unicode casing, word classes and printable characters."""
import argparse
import json
import unicodedata
from pathlib import Path

TARGET = Path(__file__).resolve().parents[2] / 'go/internal/pytext/python_case_data.go'


def render() -> str:
    lower, upper, cased, ignorable, word, printable = [], [], [], [], [], []
    for ordinal in range(0x110000):
        char = chr(ordinal)
        if char.lower() != char:
            lower.append((ordinal, char.lower()))
        if char.upper() != char:
            upper.append((ordinal, char.upper()))
        if char.isalnum() or char == "_":
            word.append(ordinal)
        if char.isprintable():
            printable.append(ordinal)
        is_cased = char.islower() or char.isupper() or char.istitle()
        if is_cased:
            cased.append(ordinal)
        # Probe the exact tables used by Python's contextual Final_Sigma rule.
        skip = (char + 'Σ ').lower().endswith('σ ') if is_cased else ('AΣ' + char + 'A').lower()[1] == 'σ'
        if skip:
            ignorable.append(ordinal)
    def ranges(values):
        out = []
        for value in values:
            if out and out[-1][1] + 1 == value:
                out[-1][1] = value
            else:
                out.append([value, value])
        return out
    lines = ['// Code generated by python/tools/export_go_unicode.py; DO NOT EDIT.',
             f'// Python Unicode database {unicodedata.unidata_version}.', 'package pytext', '',
             f'const PythonUnicodeVersion = {json.dumps(unicodedata.unidata_version)}', '']
    for name, values in [('pythonLower', lower), ('pythonUpper', upper)]:
        lines.append(f'var {name} = [...]caseMapping{{')
        lines += [f'\t{{0x{ordinal:x}, {json.dumps(value, ensure_ascii=False)}}},' for ordinal, value in values]
        lines += ['}', '']
    for name, values in [('pythonCased', cased), ('pythonCaseIgnorable', ignorable), ('pythonWord', word), ('pythonPrintable', printable)]:
        lines.append(f'var {name} = [...]caseRange{{')
        lines += [f'\t{{0x{first:x}, 0x{last:x}}},' for first, last in ranges(values)]
        lines += ['}', '']
    return '\n'.join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    output = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != output:
            print('Python Unicode casing export is stale')
            return 1
        print(f'Python Unicode casing current: {unicodedata.unidata_version}')
    else:
        TARGET.write_text(output)
        print(f'Wrote {TARGET}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
